# -*- coding: utf-8 -*-
"""decision tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5sMt-GIdRy2m0n-wH0_CAN6150zFPtM
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier,export_text,plot_tree # Make sure plot_tree is imported here

from google.colab import files
uploaded=files.upload()

df=pd.read_csv('play_tennis.csv')
df.head()

le=LabelEncoder()
df['outlook_n'] = le.fit_transform(df['outlook'])
df['temp_n'] = le.fit_transform(df['temp'])
df['humidity_n'] = le.fit_transform(df['humidity'])
df['wind_n'] = le.fit_transform(df['wind'])
df['play_n'] = le.fit_transform(df['play'])

df=df.drop(['outlook','temp','humidity','wind','play'],axis=1)

X = df.drop(['play_n','day'], axis=1)
y = df['play_n']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("Training data:")
print(X_train)
print("\nTesting data:")
print(X_test)

model = DecisionTreeClassifier(criterion='entropy')
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score # Import the accuracy_score function

from sklearn.metrics import accuracy_score # Import the accuracy_score function

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy*100:.2f}")

plt.figure(figsize=(10, 6))
plot_tree(model, feature_names=X.columns, class_names=['No', 'Yes'], filled=True)
plt.show()