# -*- coding: utf-8 -*-
"""GB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/143ZjFRvEeD4ZITggA14hcGOHCNmTfLD_
"""

import numpy as np
import matplotlib.pyplot as plt

lr=0.5

x=np.array([1,2,3,4])
y=np.array([1,2,3,4])

F0=np.mean(y)
pred=np.full(y.shape,F0,dtype=float)
print(f"Initial prediction: (F0):{F0}")

residual1=y-F0
print("Residual after iteration 0:",residual1)

def tree1(x):
  return np.where(x <= 2.5, -1, 1)
h1 = tree1(x)
F1 = F0 + lr * h1
print("Predictions after interation 1:", F1)

residual2=y-F1
print("Residual after iteration 1:",residual2)

def tree2(x):
  return np.where(x <=1.5, -1, np.where(x>=3.5 ,+1,0))
h2 = tree2(x)
F2 = F1 + lr * h2
print("Predictions after interation 2:", F2)

print("\nTrue y value: ",y)
print("Final prediction: ",F2)
print("Absolute error: ",(F2 - y))