# -*- coding: utf-8 -*-
"""hierarchy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1unj0McRGaJDLaa5nt10BNTGQqtgWjkYs
"""

import numpy as np
 from matplotlib import pyplot as plt
 from scipy.cluster.hierarchy import dendrogram, linkage

data = np.array([[18], [22], [25], [42], [27], [43]])

linked=linkage(data,method='single')

plt.figure(figsize=(8,5))

dendrogram(linked,
           orientation='top',
           labels=[18, 22, 25, 42, 27, 43],
           distance_sort='ascending',
           show_leaf_counts=True )
plt.title("Hierarchial Clustering Dendrogram")
plt.xlabel("Data points")
plt.ylabel("distance")
plt.grid(True)
plt.show()