# -*- coding: utf-8 -*-
"""hierarchy 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FLvdSj47EF7YJrYQuSH2B6GsAUMef-mY
"""

import numpy as np
from matplotlib import pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage
import pandas as pd

from google.colab import files
uploaded=files.upload()

df=pd.read_csv('wine.csv')

df.head()

df[['OD','Ash','Acl','Mg']]

df=df.head(5)

data = np.array(df[['OD','Ash','Acl','Mg']])

linked=linkage(data,method='single')

plt.figure(figsize=(8,5))

dendrogram(linked,
           orientation='top',
           distance_sort='ascending',
           show_leaf_counts=True )
plt.title("Hierarchial Clustering Dendrogram")
plt.xlabel("Data points")
plt.ylabel("distance")
plt.grid(True)
plt.show()