# -*- coding: utf-8 -*-
"""iris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uKEk4NVWQBz8cltDvMkRj-f1i4_EPOx9
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files


uploaded = files.upload()

Iris = pd.read_csv('Iris.csv')

Iris

Iris.isnull().sum()

Iris.Species.value_counts()

Iris['Species'].value_counts()

Iris['SepalLengthCm'].hist()

Iris['SepalWidthCm'].hist()

Iris['PetalLengthCm'].hist()

Iris['PetalWidthCm'].hist()

Species=['Iris-setosa','Iris-versicolor','Iris-virginica'	]

color = ['red','Blue','Orange']

for i in range(3):
      x=Iris[Iris['Species']==Species[i]]
      plt.scatter(x['SepalLengthCm'],(x['SepalWidthCm']),c=color[i],label=Species[i])
plt.xlabel('SepalLengthCm')
plt.ylabel('SepalWidthCm')
plt.legend()

M = Iris.select_dtypes(include = "number").corr()

sns.heatmap(Iris.corr(numeric_only=True), cmap='Blues', annot=True)

Iris['Species'] = Iris['Species'].astype('category')

Iris['Species'] = Iris['Species'].cat.codes

x = Iris[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y = Iris['Species']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(x_train,y_train)

prediction = model.predict(x_test)

prediction

model.score(x,y)*100