# -*- coding: utf-8 -*-
"""pca.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zDZHdr8xgQt4_SxiiHvdqjR9bPLNs6om
"""

from sklearn.datasets import load_digits
import pandas as pd
dataset=load_digits()
dataset.keys()

dataset.data.shape

dataset.data[0]

dataset.data[0].reshape(8,8)

from matplotlib import pyplot as plt
plt.gray()
plt.matshow(dataset.data[0].reshape(8,8))

plt.matshow(dataset.data[9].reshape(8,8))

dataset.target[:5]

df=pd.DataFrame(dataset.data,columns=dataset.feature_names)
df.head()

dataset.target

df.describe()

x=df
y=dataset.target

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)
x_scaled

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.2,random_state=30)

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)
model.score(x_test,y_test)

x

from sklearn.decomposition import PCA
pca=PCA(0.95)
x_pca=pca.fit_transform(x)
x_pca.shape

from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)
model.score(x_test,y_test)

pca=PCA(n_components=2)
x_pca=pca.fit_transform(x)
x_pca.shape

pca.n_components_

pca.explained_variance_ratio_

x_train_pca,x_test_pca,y_train,y_test=train_test_split(x_pca,y,test_size=0.2,random_state=30)
model=LogisticRegression(max_iter=1000)
model.fit(x_train_pca,y_train)
model.score(x_test_pca,y_test)

