# -*- coding: utf-8 -*-
"""SVC1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qQq0neGRF_C0dDK9khc6GRDqjpiY6-wn
"""

import pandas as pd
from sklearn.datasets import load_iris
iris_load = load_iris()
iris_df = pd.DataFrame(iris_load.data, columns=iris_load.feature_names)
iris_df.head()

iris_load.target_names

iris_df['target'] = iris_load.target

iris_df.head()

iris_df[iris_df.target==1].head()

iris_df['Flower_name']=iris_df.target.apply(lambda x:iris_load.target_names[x])
iris_df.head()

display(iris_df[iris_df.target==2].head())

display(iris_df[45:55])

df0=iris_df[:50]
df1=iris_df[50:100]
df2=iris_df[100:]

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

plt.xlabel('sepal length (cm)')
plt.ylabel('sepal width (cm)')
plt.scatter(df0['sepal length (cm)'], df0['sepal width (cm)'],color="green",marker='+')
plt.scatter(df1['sepal length (cm)'], df1['sepal width (cm)'],color="blue",marker='.')

plt.xlabel = 'petal length (cm)'
plt.ylabel = 'petal width (cm)'
plt.scatter(df0['petal length (cm)'], df0['petal width (cm)'],color="green",marker='+')
plt.scatter(df1['petal length (cm)'], df1['petal width (cm)'],color="blue",marker='.')

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(iris_df.drop(['target','Flower_name'],axis='columns'),iris_df.target,test_size=0.2)

len(x_train)

from sklearn.svm import SVC
model = SVC()

model.fit(x_train,y_train)

model.score(x_test,y_test)

model_c=SVC(C=10)
model_c.fit(x_train,y_train)
model_c.score(x_test, y_test)

model_c=SVC(C=1)
model_c.fit(x_train,y_train)
model_c.score(x_test, y_test)