# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wd_6QaLiGRthTETCQjh-iHXvkv6qR2CU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files


uploaded = files.upload()

df = pd.read_csv('adm_data.csv')
display(df.head())

x = df[['GRE Score','TOEFL Score','CGPA','SOP','Chance of Admit ']]
y = df['Research']

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(solver='liblinear', random_state=0)
logreg.fit(x_train, y_train)

y_pred_test = logreg.predict(x_test)
y_pred_test

new = [[314, 103,2.0,	8.21,	0.65]]
y_pred_test = logreg.predict(new)
y_pred_test

means = y_pred_test.mean()
means

if means>=0.5:
  print("Is Eligible")
else:
  print("Not Eligible")

